development:
  adapter: postgresql
  database: neighborhood_food_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: neighborhood_food_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: neighborhood_food_production
  pool: 5
  timeout: 5000